language: ruby

before_install:
  - rvm @default,@global do gem uninstall bundler -x
  - gem install bundler --version '~> 1.0.0'

rvm:
  - ree
  - 1.8.7
  - 1.9.2
  - 1.9.3

gemfile:
  - .travis/gemfiles/rails_3.0
  - .travis/gemfiles/rails_3.1
  - .travis/gemfiles/rails_3.2
  - .travis/gemfiles/rails_edge
